// Code generated by protoc-gen-go.
// source: sensors.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	sensors.proto

It has these top-level messages:
	SensorData
*/
package proto

import proto1 "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal

type SensorData struct {
	MsgId int32 `protobuf:"varint,1,opt,name=msg_id" json:"msg_id,omitempty"`
	// Sender ID to map sender to device name or so on
	SenderId  int32                 `protobuf:"varint,2,opt,name=sender_id" json:"sender_id,omitempty"`
	Timestamp int64                 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Reads     []*SensorData_Reading `protobuf:"bytes,4,rep,name=reads" json:"reads,omitempty"`
}

func (m *SensorData) Reset()         { *m = SensorData{} }
func (m *SensorData) String() string { return proto1.CompactTextString(m) }
func (*SensorData) ProtoMessage()    {}

func (m *SensorData) GetReads() []*SensorData_Reading {
	if m != nil {
		return m.Reads
	}
	return nil
}

type SensorData_Reading struct {
	Type      int32   `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Timestamp int32   `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Floatval  float32 `protobuf:"fixed32,3,opt,name=floatval" json:"floatval,omitempty"`
	Intval    int32   `protobuf:"varint,4,opt,name=intval" json:"intval,omitempty"`
}

func (m *SensorData_Reading) Reset()         { *m = SensorData_Reading{} }
func (m *SensorData_Reading) String() string { return proto1.CompactTextString(m) }
func (*SensorData_Reading) ProtoMessage()    {}
